/*---------------------------------------------------------------------------*/
/* File:        config.h                                                     */
/* Created:     Sat, 23 Jan 2010 11:11:00 GMT                                */
/*              by Oleg N. Scherbakov, mailto:oleg@7zsfx.info                */
/* Last update: Wed, 07 Mar 2018 by https://github.com/datadiode             */
/*---------------------------------------------------------------------------*/

/* custom pre-defines */
#define NO_REGISTRY
#define EXTRACT_ONLY
#define NO_READ_FROM_CODER
#define _SFX

#if defined(_DEBUG) || defined(RELEASE_DEBUG)
	#define SFXBUILD_OPTIONS2	0xffff
#endif // defined(_DEBUG) || defined(RELEASE_DEBUG)

#define SFXBUILD_OPTIONS2_COMPRESS_COPY			0x001
#define SFXBUILD_OPTIONS2_COMPRESS_BCJ			0x002
#define SFXBUILD_OPTIONS2_COMPRESS_BCJ2			0x004
#define SFXBUILD_OPTIONS2_COMPRESS_DEFLATE		0x008
#define SFXBUILD_OPTIONS2_COMPRESS_LZMA			0x010
#define SFXBUILD_OPTIONS2_COMPRESS_LZMA2		0x020
#define SFXBUILD_OPTIONS2_COMPRESS_PPMD			0x040
#define SFXBUILD_OPTIONS2_CRYPTO				0x080
#define SFXBUILD_OPTIONS2_VOLUMES				0x100
#define SFXBUILD_OPTIONS2_PROTECT				0x200
#define SFXBUILD_OPTIONS2_COMPRESS_DELTA		0x400

// 7-Zip options
#ifndef SFXBUILD_OPTIONS2
	#define SFXBUILD_OPTIONS2		0
#endif

#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_COPY) != 0 && !defined(COMPRESS_COPY)
	#define COMPRESS_COPY
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_BCJ) != 0 && !defined(COMPRESS_BCJ)
	#define COMPRESS_BCJ
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_BCJ2) != 0 && !defined(COMPRESS_BCJ2)
	#define COMPRESS_BCJ2
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_DEFLATE) != 0 && !defined(COMPRESS_DEFLATE)
	#define COMPRESS_DEFLATE
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_LZMA) != 0 && !defined(COMPRESS_LZMA)
	#define COMPRESS_LZMA
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_LZMA2) != 0 && !defined(COMPRESS_LZMA2)
	#define COMPRESS_LZMA2
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_PPMD) != 0 && !defined(COMPRESS_PPMD)
	#define COMPRESS_PPMD
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_CRYPTO) == 0 && !defined(SFX_CRYPTO)
	#define _NO_CRYPTO
#else
	#ifndef SFX_CRYPTO
		#define SFX_CRYPTO
	#endif // SFX_CRYPTO
	#ifdef _NO_CRYPTO
		#undef _NO_CRYPTO
	#endif // _NO_CRYPTO
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_VOLUMES) != 0 && !defined(SFX_VOLUMES)
	#define SFX_VOLUMES
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_PROTECT) != 0 && !defined(SFX_PROTECT)
	#define SFX_PROTECT
#endif
#if (SFXBUILD_OPTIONS2&SFXBUILD_OPTIONS2_COMPRESS_DELTA) != 0 && !defined(COMPRESS_DELTA)
	#define COMPRESS_DELTA
#endif

#ifndef COMPRESS_COPY
	#undef SFXBUILD_OPTIONS2_COMPRESS_COPY
	#define SFXBUILD_OPTIONS2_COMPRESS_COPY		0
#endif
#ifndef COMPRESS_BCJ
	#undef SFXBUILD_OPTIONS2_COMPRESS_BCJ
	#define SFXBUILD_OPTIONS2_COMPRESS_BCJ		0
#endif
#ifndef COMPRESS_BCJ2
	#undef SFXBUILD_OPTIONS2_COMPRESS_BCJ2
	#define SFXBUILD_OPTIONS2_COMPRESS_BCJ2		0
#endif
#ifndef COMPRESS_DEFLATE
	#undef SFXBUILD_OPTIONS2_COMPRESS_DEFLATE
	#define SFXBUILD_OPTIONS2_COMPRESS_DEFLATE	0
#endif
#ifndef COMPRESS_LZMA
	#undef SFXBUILD_OPTIONS2_COMPRESS_LZMA
	#define SFXBUILD_OPTIONS2_COMPRESS_LZMA		0
#endif
#ifndef COMPRESS_LZMA2
	#undef SFXBUILD_OPTIONS2_COMPRESS_LZMA2
	#define SFXBUILD_OPTIONS2_COMPRESS_LZMA2	0
#endif
#ifndef COMPRESS_PPMD
	#undef SFXBUILD_OPTIONS2_COMPRESS_PPMD
	#define SFXBUILD_OPTIONS2_COMPRESS_PPMD		0
#endif
#ifdef _NO_CRYPTO
	#undef SFXBUILD_OPTIONS2_CRYPTO
	#define SFXBUILD_OPTIONS2_CRYPTO			0
#endif
#ifndef SFX_VOLUMES
	#undef SFXBUILD_OPTIONS2_VOLUMES
	#define SFXBUILD_OPTIONS2_VOLUMES			0
#endif
#ifndef SFX_PROTECT
	#undef SFXBUILD_OPTIONS2_PROTECT
	#define SFXBUILD_OPTIONS2_PROTECT			0
#endif
#ifndef COMPRESS_DELTA
	#undef SFXBUILD_OPTIONS2_COMPRESS_DELTA
	#define SFXBUILD_OPTIONS2_COMPRESS_DELTA	0
#endif

#undef SFXBUILD_OPTIONS2
#define SFXBUILD_OPTIONS2					\
	SFXBUILD_OPTIONS2_COMPRESS_COPY		|	\
	SFXBUILD_OPTIONS2_COMPRESS_BCJ		|	\
	SFXBUILD_OPTIONS2_COMPRESS_BCJ2		|	\
	SFXBUILD_OPTIONS2_COMPRESS_DEFLATE	|	\
	SFXBUILD_OPTIONS2_COMPRESS_LZMA		|	\
	SFXBUILD_OPTIONS2_COMPRESS_LZMA2	|	\
	SFXBUILD_OPTIONS2_COMPRESS_PPMD		|	\
	SFXBUILD_OPTIONS2_CRYPTO			|	\
	SFXBUILD_OPTIONS2_VOLUMES			|	\
	SFXBUILD_OPTIONS2_PROTECT			|	\
	SFXBUILD_OPTIONS2_COMPRESS_DELTA	|	\
	0
